Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from .views import * 
from django.urls import path 


urlpatterns = [
    path('', index, name="index"),
    path('upload/', uploadImage, name="upload"),
    path('create_category/', create_category, name="create_category"),
    path('create_book/', create_book, name="create_book"),
    path('<int:id>/', details, name="details")
]


app_name = "book"

users/urls.py
from django.urls import path 
from . import views 


urlpatterns = [
    path('register/', views.registerUsers, name="register"),
    path('login/', views.login, name="login"),
    path('logout', views.user_logout, name="logout"),
]


app_name = "users"

books/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=50)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    
    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200,unique=True, null=False, blank=False)
    author = models.CharField(max_length=200,null=False, blank=False)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    
    def __str__(self):
        return self.title
    

class BookImage(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    image = models.ImageField(upload_to='books')
    
    def __str__(self):
        return self.name

users/models.py
from django.db import models

# Create your models here.

books/forms.py
from django import forms
from .models import Book, Category


class LoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50) 
    

class CategoryForm(forms.ModelForm):
    name = forms.CharField(
        max_length=20, 
        min_length=3, 
        required=True,
    )
    class Meta:
        model = Category
        fields = ['name']


class BooksForm(forms.ModelForm):
    title = forms.CharField(max_length=50, min_length=10, required=True)
    author = forms.CharField(max_length=50, min_length=10, required=True)
    class Meta:
        model = Book
        fields = ['title', 'author', 'description', 'category']
    

books/views.py
from django.shortcuts import render, redirect
from .models import Book, Category, BookImage
from .forms import BooksForm, CategoryForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.models import Permission
from django.contrib.auth.decorators import login_required

@login_required(login_url='users:login')
def index(request):
    
    books = Book.objects.all()
    return render(
        request,
        'books/index.html',
        {"books":books}
    )
@login_required(login_url='users:login')
def details(request, id):
    book = Book.objects.get(id=id)
    return render(
        request,
        'books/details.html',
        {"book":book}
    )
    
@login_required(login_url='users:login')
def create_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('book:index')
        else: 
            form = CategoryForm()
            messa = messages.error(request, form.errors)
            return render(
                request,
                'books/create_category.html',
                {"form":form, 'messa':messa}
            )
    else:
        form = CategoryForm()
        return render(
            request,
            'books/create_category.html',
            {"form":form}
        )
@login_required(login_url='users:login')  
def create_book(request):
    if request.method == 'POST':
        form = BooksForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('book:index')
        else: 
            form = BooksForm(instance=request.POST)
            messa = messages.error(request, form.errors)
            return render(
                request,
                'books/create_book.html',
                {"form":form, 'messa':messa}
            )
    else:
        form = BooksForm()
        return render(
            request,
            'books/create_book.html',
            {"form":form}
        )
        
        
@login_required(login_url='users:login')      
def uploadImage(request):
    if request.method == 'POST':
        if request.FILES:
            image = request.FILES['image']
            name = request.POST['name']
            BookImage.objects.create(name=name, image=image)
        return redirect('book:index')

    else:
        return render(
            request,
            'books/upload.html'
        )

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth import login as auth_login

# Create your views here.
def registerUsers(request):
    if request.user.is_authenticated:
        return redirect('book:index')
    
    if request.method == 'POST':
       username = request.POST['username']
       first_name = request.POST['first_name']
       last_name = request.POST['last_name']
       email = request.POST['email']
       password = request.POST['password']
       
       User.objects.create_user(
           username = username, 
           first_name= first_name, 
           last_name= last_name, 
           email= email, 
           password= password, 
        )
       return redirect('users:login')
       
    else:
        return render(
            request,
            'users/register.html'
        )
        
        
def login(request):
    if request.user.is_authenticated:
        return redirect('book:index')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        
        user_ = User.objects.filter(username=username).first()
        
        if user_:
            user = authenticate(username=username, password=password)
            
            if user:
                auth_login(request, user)
                return redirect('book:index')
            else:
                messages.add_message(request, messages.ERROR, "Username or Password is Incorrect")
            
                return render(
                    request,
                    'users/login.html'
                ) 
        else:
            return redirect('users:register')
       
    else:
        return render(
            request,
            'users/login.html'
        )
        

def user_logout(request):
    logout(request)
    return redirect('users:login')

books/templates/books/create_book.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <form action={% url 'book:create_book' %} method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Submit</button>
        </form>

        {% if messa %}
            <ul class="messages">
                {% for message in messa %}
                <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{
                    message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

    </body>
</html>

books/templates/books/create_category.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <form action={% url 'book:create_category' %} method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Submit</button>
        </form>

        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{
                message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

    </body>
</html>

books/templates/books/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Books Lib</title>
</head>
<style>
    .page{
        background-color: black;
        height: 100vh;
        width: 100vh;
        justify-content: center;
        align-items: center;
        display: flex;

    }
    .main{
        height: 800px;
        width: 800px;
        margin:auto auto;

        background-color: white;
    }

</style>

<body class="page">
    <div class="main">
        <ul>
            <li>{{book.title}}</li>
            <li>{{book.author}}</li>
            <li>{{book.description}}</li>
            <li>{{book.category}}</li>
        </ul>

        <a class="btn btn-primary" href="/" role="button">Home</a>
    </div>
</body>
</html>

books/templates/books/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Books Lib</title>
</head>
<style>
    .page{
        height: 100vh;
        width: 100vh;
        justify-content: center;
        align-items: center;
        display: flex;

    }
    .main{
        height: 800px;
        width: 800px;
        margin:auto auto;

        background-color: white;
    }
    .hide{
        display:none;
    }

</style>

<body class="page">
    <div class="main">
        {% if request.user.is_authenticated %}
            <a href={% url 'users:logout'  %} >Logout</a>
        {% endif %}
        <ul>
            {% for book in books %}
                <li><a href={% url 'book:details' book.id  %}>{{book.title}}</a></li>
            {% endfor %}
        </ul>


        <a href={% url 'book:create_category' %} >Create Category </a>
        <a href={% url 'book:create_book' %} >Create Book </a>


        <img 
            src="{% static 'images/img.jpg' %}" 
            alt="image"
            height="200px"
            width="200px" 
            id="image" 
        />
    </div>

   
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

books/templates/books/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Books Lib</title>
</head>
<style>
    .page{
        background-color: black;
        height: 100vh;
        width: 100vh;
        justify-content: center;
        align-items: center;
        display: flex;

    }
    .main{
        height: 800px;
        width: 800px;
        margin:auto auto;

        background-color: white;
    }

</style>

<body class="page">
    <div class="main">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="text" name="name" id="title" placeholder="Enter the name">
            <input type="file" name="image" id="file">
            <input type="submit">
        </form>
    </div>
</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Books Lib</title>
    </head>
    <style>
    .page{
        background-color: black;
        height: 100vh;
        width: 100vh;
        justify-content: center;
        align-items: center;
        display: flex;

    }
    .main{
        height: 800px;
        width: 800px;
        margin:auto auto;

        background-color: white;
    }

</style>

    <body class="page">
        <div class="main">
            <form method="POST" action>
                {% csrf_token %}
                <input type="text" name="username" id="title"
                    placeholder="Enter the username">
                <input type="password" name="password" id="title"
                    placeholder="Enter the password">
                <input type="submit">
            </form>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Books Lib</title>
</head>
<style>
    .page{
        background-color: black;
        height: 100vh;
        width: 100vh;
        justify-content: center;
        align-items: center;
        display: flex;

    }
    .main{
        height: 800px;
        width: 800px;
        margin:auto auto;

        background-color: white;
    }

</style>

<body class="page">
    <div class="main">
        <form method="POST" action="">
            {% csrf_token %}
            <input type="text" name="username" id="title" placeholder="Enter the username">
            <input type="text" name="first_name" id="title" placeholder="Enter the first name">
            <input type="text" name="last_name" id="title" placeholder="Enter the last name ">
            <input type="email" name="email" id="title" placeholder="Enter the email">
            <input type="password" name="password" id="title" placeholder="Enter the password">
            <input type="submit">
        </form>
    </div>
</body>
</html>